schema_version: 1

context:
  version: "1.2.0"

package:
  name: tprof
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tprof/tprof-${{ version }}.tar.gz
  sha256: 4e6af4b61006dc4f52c84f7b51cb5355533b42eea16908669c3ea671450f9b0e

build:
  number: 0
  skip: match(python, "<3.12")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - tprof = tprof.main:main

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
  host:
    - python
    - setuptools >=77
    - pip
  run:
    - python
    - rich >=14.2

tests:
  - python:
      imports:
        - tprof
  - requirements:
      run:
        - pip
    script:
      - pip check
      - tprof --help

about:
  summary: A targeting profiler.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/adamchainz/tprof

extra:
  recipe-maintainers:
    - thewchan
